id: PD77FB7D7
initial_creation_type: input
source_metadata:
  title: Lala Sonam Chödrup Series
  language: en
  description: Lala Sönam Chödrup (glag bla bsod nams chos 'grub, 1862–1944) of Nyarong
    was regarded as a speech emanation of Dzogchen Pema Rigdzin. He is best-known
    for his biography of Longchenpa and his commentary on the Aspiration of Sukhāvatī.
  volume:
    56b691f61dbb4228ad27dd301a66e6e2:
      title: Prayer of Aspiration Incorporating the Eight Thoughts of Great Beings
        Who Follow the Way of the Mahāyāna
      parent: Aspiration Prayers
    ff8ce291a0a34179a9d2fb550006d880:
      title: A Brief Guide to Samaya Commitment
      parent: Samaya
created_at: '2022-03-01T00:33:14.571439'
last_modified_at: '2022-03-01T00:33:14.571445'
